name: Update Translation Progress

on:
  push:
    branches:
      - main
    paths:
      - 'data/lang/**'
  workflow_dispatch:
jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run translation update script
      run: |
        python devtools/translate-readme.py

    - name: Commit and push changes using Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        git add README.md
        git commit -m "Update translation progress"
        
        # Push the changes to the 'main' branch
        git push
